### ISSUE TITLE
issues when building for ECP5

### ISSUE THREAD

**Issue by juanschroeder** [nathanrossi/meta-hdl#14]
Hi Nathan,

Thanks a lot for your work.

Trying to do the build for versa-ecp5 I found the following problems in meta-hdl (using current master):

-  the checksum for the licenses (in LIC_FILES_CHKSUM) for litespi and litex-pythondata-software-picolibc recipes are incorrect. When the build fails it gives the value that should be in the recipes

-  The build for linux-on-litex-vexriscv fails when building bios.elf. The problem seems to be the toolchain and the fact that a linux toolchain (provided by meta-oe?) is used instead of a bare-metal toolchain. I don't know what would be the best way to fix this. As a test I prepended PATH with the toolchain mentioned in linux-on-litex-vexriscv repository (installed in my build PC) so that the wrappers generated in do_create_toolchain_wrappers() in litexnative.bbclass point to this toolchain, and the it stopped failing.

- The name of the generated .bit and .svf files are hardcoded to "top.bit" and "top.svf" in linux-on-litex-vexriscv.bb but for this target the generated files are "versa_ecp5.bit" and "versa_ecp5.svf".

If there is any stable tag/commit I should be using instead of 'master' branch please let me know.

I would also like to know if anyone could tell me how much work it would take to make this build work for a Xilinx Nexys4DDR target, either with the Vivado toolchain or with the open source ones.

Thanks!

**Comment by nathanrossi** [comment]
I have pushed some commits to sort out the `LIC_FILES_CHKSUM` and `.bit`/`.svf` deploying.

However I don't see any errors or failures building the `linux-on-litex-vexriscv` recipe. Can you provide the error you see and the associated build configuration when you run bitbake. The litex project recently changed to using picolibc, however there is an odd dependency with picolibc where it depends on a toolchain that is not baremetal (e.g. newlib or glibc) for standard headers.

As for getting the build working for the Xilinx Nexys4DDR, it would be a matter of creating a recipe similar to the existing `linux-on-litex-vexriscv.bb` and sourcing the Xilinx tools install within the `do_compile`. I had looked at enabling access to the Xilinx tools from within OE previously (https://github.com/nathanrossi/meta-hdl/commits/xilinx-tools) which might be of help.

**Comment by nathanrossi** [comment]
I discovered an issue where linux-on-lttex-vexriscv would fail to compile correctly when using the poky distro. This is likely the issue mentioned in second point. The error seen is similar to below:

```
| tmp/work/versa_ecp5-poky-linux/linux-on-litex-vexriscv/0+gitAUTOINC+708b0cbf31-r0/recipe-sysroot-native/usr/bin/riscv32-poky-linux/../../libexec/riscv32-poky-linux/gcc/riscv32-poky-linux/11.2.0/ld: ../libc/libc.a(libc_ssp_chk_fail.c.o): in function `__chk_fail':
| tmp/work/versa_ecp5-poky-linux/linux-on-litex-vexriscv/0+gitAUTOINC+708b0cbf31-r0/git/build/lattice_versa_ecp5/software/libc/../../../../../recipe-sysroot-native/usr/lib/python3.10/site-packages/pythondata_software_picolibc/data/newlib/libc/ssp/chk_fail.c:13: undefined reference to `write'
| collect2: error: ld returned 1 exit status
| make: *** [tmp/work/versa_ecp5-poky-linux/linux-on-litex-vexriscv/0+gitAUTOINC+708b0cbf31-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/litex/soc/software/bios/Makefile:68: bios.elf] Error 1
```

I have resolved this in https://github.com/nathanrossi/meta-hdl/commit/98b86e735e1ca95d0088a023621b81e0aff0dddd.

I will close this issue, if you still see errors building please re-open/comment on this issue with the exact error you observe.
