### ISSUE TITLE
Add Project X-Ray to fpga-tools

### ISSUE THREAD

**Issue by mithro** [nathanrossi/meta-hdl#3]
Similar to Project Trellis, Project X-Ray aims to support Xilinx 7-series bit stream format.

> ### Project X-Ray
> Project X-Ray aims at documenting the Xilinx 7-series bit-stream format, a prerequisite to building Open Source tools to generate bit-streams for those devices. The information currently on this page is a sneak preview for the kind of information Project X-Ray will provide.

**Comment by nathanrossi** [comment]
I have added some recipes for prjxray. See https://github.com/nathanrossi/meta-hdl/tree/master/recipes-fpga/prjxray

@mithro I noticed this project has quite a number of dependencies provided by submodules are you aware if the intention is to continue that practice?

My understanding is that prjxray is only used within the a vpr flow at the moment. As mentioned on #2 do you have an example flow so I can test the dependencies between these projects.

**Comment by mithro** [comment]
@nathanrossi At the moment prjxray isn't used except in the SymbiFlow architecture definitions -> https://github.com/SymbiFlow/symbiflow-arch-defs

**Comment by nathanrossi** [comment]
A recipe for this is in meta-hdl, https://github.com/nathanrossi/meta-hdl/blob/master/recipes-fpga/prjxray/prjxray.bb

And a recipe for symbiflow-arch-defs (https://github.com/nathanrossi/meta-hdl/blob/wip/recipes-fpga/symbiflow/symbiflow-arch-defs.bb) is queued pending an upstream pull request.
