### ISSUE TITLE
Correct place for lm32 cross compiler?

### ISSUE THREAD

**Issue by mithro** [nathanrossi/meta-hdl#4]
We frequently use the [LatticeMico32 soft-CPU from Lattice](http://www.latticesemi.com/en/Products/DesignSoftwareAndIP/IntellectualProperty/IPCore/IPCores02/LatticeMico32.aspx) in our FPGA designs. For this we need a `lm32` cross compiler. The `lm32` architecture is in upstream binutils and gcc, so in theory should be pretty easy to support?

Unlike RISC-V the LatticeMico32 is pretty much **only** ever used on FPGAs as a soft-core. Where would be the correct place to add this cross compiler? Would it make sense to be part of this repository?

**Comment by nathanrossi** [comment]
Since the toolchain is all upstream the best place for the setup of the LatticeMico32 would be the oe-core/meta layer. There would be very little to configure since its not a linux target (or at least not with glibc/musl). Probably looking at just setting up the `classes/siteinfo.bbclass` and `lib/oe/elf.py` and maybe adding some tunes like microblaze has.

**Comment by nathanrossi** [comment]
So it appears it would be relatively easy to enable lm32. With the following branch https://github.com/nathanrossi/openembedded-core/tree/nrossi/lm32 I was able to build compiler and newlib.

@mithro Do you know of any example projects for the lm32? Something that runs with the qemu model would make it easy to test if the compiler works as intend.

**Comment by mithro** [comment]
[NuttX has a lm32 port](http://nuttx.org/doku.php?id=documentation:about)? See https://www.youtube.com/watch?v=pWvVY7n3mZ8 for example.

**Comment by nathanrossi** [comment]
Thanks @mithro, grabbed some of the content from nuttx and made a quick test program.

https://gist.github.com/nathanrossi/56c6b712a268ffe0656f2e0c48d6ee2c

The compiler appears to work correctly, including linking with libgcc.

```
0x00000000 - hello world, long string really long string
0x00000064 / 10 = 0x0000000a
0x00000001 - hello world, long string really long string
0x00000064 / 10 = 0x0000000a
0x00000002 - hello world, long string really long string
0x00000064 / 10 = 0x0000000a
```

I had some additional QEMU setup changes to the previous mentioned oe-core branch here: https://github.com/nathanrossi/openembedded-core/tree/nrossi/lm32. I will look at cleaning up some of the patches and submitting them to oe-core.

**Comment by mithro** [comment]
This is the testing we do for the lm32 gcc,
```shell
# Check the compiler can build a simple C app which requires the standard
# library.

echo "==========================================="

echo "Compile and link a 'bare metal' binary"

cat > main.c <<EOF
int main() {
	volatile int i = 0;
	for (; i < 0; i++);
	return 0;
}
EOF

echo "Compiling main"
$GCC -c main.c -o main.o
SUCCESS=$?
if [ $SUCCESS -ne 0 ]; then
	echo "Compiler didn't exit successfully."
	exit 1
fi

if [ ! -e main.o ]; then
	echo "Compiler didn't make a binary output file!"
	exit 1
fi

echo "Info about main.o"
file main.o
$TARGET-objdump -f ./main.o

if ! $TARGET-objdump -f ./main.o | grep -q 'architecture: lm32'; then
	echo "Compiled binary output not correct architecture!"
	exit 1
fi

echo "Linking main.elf"
cat > main.ld <<EOF
SECTIONS
{
  . = 0x10000;
  .text : { *(.text) }
  . = 0x80000;
  .data : { *(.data) }
  .bss : { *(.bss) }
}
EOF

$TARGET-ld -T main.ld -o ./main.elf main.o -M
SUCCESS=$?
if [ $SUCCESS -ne 0 ]; then
	echo "Linker didn't exit successfully."
	exit 1
fi

echo "Info about main.elf"
file main.elf
$TARGET-objdump -f ./main.elf

echo "==========================================="

echo "Making sure we don't have any libc available"

cat > stdio1.c <<EOF
#include <stdio.h>
int main() {
	puts("Hello world\n");
	return 0;
}
EOF

echo "Compiling stdio1 (should fail!)"
$GCC -c stdio1.c -o stdio1.o
SUCCESS=$?
if [ $SUCCESS -eq 0 ]; then
	echo "Compiler has standard library!"
	exit 1
fi

echo "==========================================="

echo "Don't include the header and try to link.."
cat > stdio2.c <<EOF
int main() {
	puts("Hello world\n");
	return 0;
}
EOF

echo "Compiling stdio2"
$GCC -c stdio2.c -o stdio2.o -Wno-implicit-function-declaration
SUCCESS=$?
if [ $SUCCESS -ne 0 ]; then
	echo "Compiler wasn't able to compile stdio2.c"
	exit 1
fi

echo "Trying to link stdio2 (should fail!)"
cat > stdio2.ld <<EOF
SECTIONS
{
  . = 0x10000;
  .text : { *(.text) }
  . = 0x80000;
  .data : { *(.data) }
  .bss : { *(.bss) }
}
EOF
$TARGET-ld -T stdio2.ld -o ./stdio2.elf stdio2.o
SUCCESS=$?
if [ $SUCCESS -eq 0 ]; then
	echo "Linker was able to find puts!"
	exit 1
fi
```

**Comment by nathanrossi** [comment]
@mithro I tested your test script and there were no issues, although I did need to supply `-nostdlib -nostdinc` since the toolchain is configured as a newlib toolchain.

Also I went ahead and sent the 3 lm32 patches for oe-core to the mailing list.
https://patchwork.openembedded.org/series/14171/

**Comment by mithro** [comment]
When / how should I test this?

**Comment by nathanrossi** [comment]
You can test it now if you would like. I suspect you would like to test it as if it was a pre-built toolchain outside of the OE build environment, so the following steps describe how to build a portable toolchain tarball for use within your own environment.

This is all based on using the oe-core branch here: https://github.com/nathanrossi/openembedded-core/tree/nrossi/lm32. This repo is not poky so you will need to grab bitbake (http://git.openembedded.org/bitbake/) as well, just clone it inside the openembedded-core repo.

1. Setup a build environment, with `oe-init-build-env`
2. Set `MACHINE = "lm32"`
3. `bitbake meta-toolchain`, wait for build to complete
4. Grab toolchain from `tmp-newlib/deploy/sdk/` or run it directly
5. `./oecore-x86_64-lm32-toolchain-nodistro.0.sh -d <install path>` to extract the toolchain
6. `. <install path>/environment-setup-lm32-oe-elf` to setup environment variables
7. `lm32-oe-elf-gcc` should be on the path

**Comment by mithro** [comment]
I don't quite get how openembedded-core relates to these types of instructions;
```shell
git clone git://git.yoctoproject.org/poky
cd poky
. ./oe-init-build-env
MACHINE=qemuarm bitbake core-image-minimal

cd ..
git clone https://github.com/nathanrossi/meta-hdl
git clone git://git.openembedded.org/meta-openembedded
# Add meta-hdl and meta-openembedded/meta-oe to build/conf/bblayers.conf
# Comment out the DISTRO=poky option?
MACHINE=picosoc bitbake picosoc-hx8k
```

**Comment by nathanrossi** [comment]
@mithro Poky is just a repo merge of oe-core + bitbake + meta-yocto. So your poky clone:
```
git clone git://git.yoctoproject.org/poky
cd poky
```

Becomes:
```
git clone git://git.openembedded.org/openembedded-core
cd openembedded-core
git clone git://git.openembedded.org/bitbake
```

To use my branch just add the remote (to the `openembedded-core` repo) and checkout.

On a side note it looks like the patches have been merged to oe-core master. Though you still need the `lm32.conf` machine, I will add that to meta-hdl to keep track of it for now.

**Comment by nathanrossi** [comment]
I am going to go ahead and close this issue. I have not seen any issues with it being able to build a variety of programs. Feel free to open another issue if any problems arise.
