### ISSUE TITLE
Does it make sense for programming tools to be part of this layer?

### ISSUE THREAD

**Issue by mithro** [nathanrossi/meta-hdl#5]
Most FPGAs need some type of tool to program them (normally via USB). Does it make sense for these programming tools to be part of this layer?

Some examples that would be good to support;
 * [OpenOCD](http://openocd.org/)
 * iceprog from icetime
 * [xc3sprog](http://xc3sprog.sourceforge.net/)
 * [tinyprog](https://tinyfpga.com/bx/guide.html)

**Comment by nathanrossi** [comment]
Yes FPGA related programmers tools make sense to be in meta-hdl unless their is a better location for them.

For example OpenOCD is not just for FPGA's and there is already a recipe in meta-oe for it, see http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-devtools/openocd/openocd_git.bb?h=master

As for `iceprog`, the `icestorm` recipe already builds `iceprog` (https://github.com/nathanrossi/meta-hdl/blob/master/recipes-fpga/icestorm/icestorm_git.bb#L20) by default along with `libftdi` from meta-oe.

For tinyprog I had looked at adding it the other day, however it depends on quite a few python libraries that are not in any OE layers so they will need to be created as recipes too (which can live in meta-hdl).

As for xc3sprog, I have not looked into it but I imagine it should be relatively straight forward to include a recipe for.

**Comment by nathanrossi** [comment]
I have added recipes for tinyprog (d750c41552858480d820b08089837a4ba292c006) and xc3sprog (50b71de6bb5d08f023cfd987cd58ed3a03ae5e43) as suggested. For now closing this issue as all the listed programs are available, for any additional ones please open up a new issue.
