### ISSUE TITLE
Add support for LiteX and friend repositories

### ISSUE THREAD

**Issue by mithro** [nathanrossi/meta-hdl#6]
* https://github.com/enjoy-digital/

The "big three" would be;
 - [ ] litex
 - [ ] liteeth
 - [ ] litedram

The smaller ones would be;
 - [ ] litepcie  
 - [ ] litescope  
 - [ ] litevideo
 - [ ] litesata
 - [ ] liteusb

**Comment by mithro** [comment]
Example migen receipe at https://github.com/nathanrossi/meta-hdl/commit/b8b45708ccbfc95bae4716592894b5f58a9b6042#diff-f98e6fb1f28d2f22cf691c93008fef91

**Comment by nathanrossi** [comment]
Recipes for litex and lite* cores (excluding liteusb which is deprecated) are now available in master.
